server:
   port: 8761
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
       defaultZone: http://admin:admin@localhost:${server.port}/eureka/
spring:
  application:
    name: eureka-server-8761
  security:
    user:
      name: admin
      password: admin
