server:
   port: 1111
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
       defaultZone: http://localhost:${server.port}/eureka/
spring:
  application:
    name: eureka-server-8761