# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fly_blog
    username: root
    password: admin
#redis
  redis:
    sentinel: mymaster
      master: 47.106.38.101:26379,47.106.38.101:26380

